openapi: "3.0.0"


info:
  version: "1.0"
  title: Insight Object Graph API
  description: Retrieve Insight data as object graph


servers:
  - url: /rest/insight-object-graph/1.0


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic


security:
  - basicAuth: []


paths:

  /graph/{insight_object_id}:
    get:
      summary: Returns the object graph with the given Insight object as root.
      parameters:
        - in: path
          name: insight_object_id
          required: true
          schema:
            type: integer
        - in: query
          name: blacklist_relations
          description: Set of relation names (on any object) to exclude
          required: false
          schema:
            type: array
            items:
              type: string
        - in: query
          name: whitelist_relations
          description: Set of relation names (on any object) to include (exclusively)
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: JSON representing the object graph
          content:
            application/json:
              example:
                [{
                   "id": 39328,
                   "typeId": 32,
                   "schemaId": 82,
                   "attributes":
                     [{
                        "id": 634223,
                        "typeId": 1535,
                        "name": "someAttribute",
                        "values": ["value 1", "value 2"]
                      }],
                   "relations":
                     [{
                        "id": 23423,
                        "typeId": 1536,
                        "name": "someRelation",
                        "values": [832492, 23729]
                      }],
                   "inverseRelations":
                     [{
                        "name": "someInverseRelation",
                        "objects": [2342]
                      }]
                 }]
        '404':
          description: Insight Object not found
