openapi: "3.0.0"


info:
  version: "1.0"
  title: Insight Object List
  description: Retrieve all Insight objects of given Type


servers:
  - url: /rest/insight-object-graph/1.0


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic


security:
  - basicAuth: []


paths:

  /objects/{object-type-name}:
    get:
      summary: Returns all Insight objects of the given object type, including all attributes.
      description: Children of the object type are considered as well.
      parameters:
        - in: path
          name: object-type-name
          required: true
          schema:
            type: string
        - in: query
          name: schemaId
          description: Optionally restrict results to specific Insight Object Schema
          required: false
          schema:
            type: integer
        - in: query
          name: attributes
          description: Optionally restrict results to specific attributes (case-sensitive)
          required: false
          schema:
            type: array
            items:
              type: string
        - in: query
          name: resolve_attributes
          description: Optionally restrict results to specific attributes (case-sensitive) and resolve relation ID
          required: false
          schema:
            type: array
            items:
              type: string
        - in: query
          name: resolve_relations
          description: Optionally resolve ALL attribute relation IDs to names of connected objects
          schema:
            type: boolean
        - in: query
          name: iql_string
          description: 'Optionally pass additional iql query to be applied.
                        if your query consists of multiple statements, wrap them in parenthesis as it will be
                        concatenated with another query'
          schema:
            type: string
      responses:
        '200':
          description: JSON representing list of Insight Objects
          content:
            application/json:
              example:
                [{
                   "id": 1,
                   "attributes":
                     [{
                        "name": "Key",
                        "values": ["IT-1"]
                      },
                      {
                        "name": "Name",
                        "values": ["SomeName"]
                      },
                      {
                        "name": "AttributeXY",
                        "values": ["SomeAttributeValue"]
                      }]
                 }]
        '404':
          description: No objects found
