openapi: "3.0.0"


info:
  version: "1.0"
  title: Jira Issues with related Insight Objects
  description: Retrieve all Issues with related objects in the given insight-object-field.


servers:
  - url: /rest/insight-object-graph/1.0


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic


security:
  - basicAuth: []


paths:

  /issues/{insight-object-field-name}:
    get:
      summary: Returns all Jira Issues with an object relation in the given {insight-object-field-name}.
      parameters:
        - in: path
          name: insight-object-field-name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: JSON representing list of Jira Issues
          content:
            application/json:
              example:
                [{
                   "id": 39328,
                   "fields":
                     [{
                        "name": "Key",
                        "values": ["TEST-1"]
                     },
                     {
                        "name": "Summary",
                        "values": ["New Issue to Site"]
                     },
                     {
                        "name": "AttributeXY",
                        "values": ["ValueXY"]
                     }]
                 }]
        '404':
          description: No issues found
