# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with maven
        run: mvn -B package --file pom.xml

      - shell: bash
        env:
          LINK_TIME_ARTIFACTORY_USERNAME: ${{ secrets.LINK_TIME_ARTIFACTORY_USERNAME }}
          LINK_TIME_ARTIFACTORY_PASSWORD: ${{ secrets.LINK_TIME_ARTIFACTORY_PASSWORD }}
        run: |
          pipelines/configure-maven-artifactory.sh $HOME/.m2/settings.xml

      - name: Publish to artifactory
        run: mvn deploy -q -Pci
